[3주차] 실습
GDG-INU/spring-advanced-1st pull request #7
Opened 2024-11-08 15:31 UTC by chaeeun1103

## #️⃣연관된 이슈

> ex) close #이슈번호

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-11-13 13:38 UTC, jang-namu requested changes
3주차 실습, 고생하셨습니다!
몇 가지 코멘트를 추가했어요.
우리가 지금까지 얘기해왔던 것들.. 그리고 일반적인 프랙티스들을 위주로 고민해볼 부분들을 작성했어요.
생각해보시고 괜찮을 것 같은 내용들을 적용해보세요.
4주차도 화이팅입니다~!!

2024-11-13 13:38 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Author.java
> +}
사용하지않는 메서드는 삭제하는게 좋아요!
그리고 setter를 사용하게되면 엔티티의 상태가 변경되는 이유를 드러내기가 힘들 수 있어요.
첫 시간에 우리가 함께 얘기했던 setter를 지양해야하는 이유에 대해 알아볼까요?

2024-11-13 13:38 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Author.java
> +public class Author {
클래스에 아무런 생성자도 지정하지 않으면 어떻게 될까요??

2024-11-13 13:38 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/AuthorService.java
> +    private AuthorRepository authorRepository;
Author와 Publishr 서비스에서는 private으로 썼고, BookService에서는 private final로 작성하셨네요!
두 가지 중 어떤 방법이 더 좋을까요?

2024-11-13 13:38 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/AuthorService.java
> +    }
아래 두 서비스를 포함해서, 서비스가 단순히 레포지토리의 메서드를 호출하고, 그 값을 그대로 반환하고 있어요.
현재 상태로는 엔티티 객체가 서비스 외부로 그대로 노출되서, 여러곳에서 변경될 위험이 있을 것 같아요!
이를 막기 위해서 어떤 조치를 취할 수 있을까요? 지난 시간에 얘기했던 각 레이어의 책임과 DTO와 도메인 객체의 분리에 대해 고민해볼까요?

2024-11-13 13:38 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/PublisherController.java
> +    private PublisherService publisherService;
Auth/BookController와 달리 해당 클래스에는 서비스가 final로 선언되어 있지않아요!

2024-11-13 13:38 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/AuthorController.java
> +    }
DTO와 엔티티의 분리가 이뤄지지 않아서 서비스를 넘어 컨트롤러의 반환값까지 엔티티가 전달되고 있어요.
getAuthor에서는 Optional이 그대로 반환되고 있어서, 클라이언트가 명시적으로 null 처리를  해주지 않으면 오류가 발생할 수 있어요.
DTO와 엔티티의 분리에 대해서 생각하면서, 어떻게하면 좋을지 고민해보세요!

2024-11-13 13:38 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/AuthorController.java
> +    }
Author의 구조를 외부에 공개하면, 추후 Author의 필드가 변경될 때 많은 클라이언트 코드가 같이 변경되어야 해요.
Author의 구조를 공개하지 않으면서 추후 내부 표현 방식 변경에 유연하게 할 수 있을까요?

2024-11-13 13:38 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/BookController.java
아래 getBookTitle()의 엔드포인트는 '/books/title?title=어린왕자'와 같이 어색할 수 있을 것 같아요.
'/books?title=어린왕자' 또는 '/books/search?title=어린왕자'와 같은 방식은 어떨까요?

추가적으로 책 제목으로 검색하게 되면, 콜렉션을 반환하는게 더 자연스러울 것 같아요!

2024-11-13 17:00 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Author.java
> +}
오오,, 그렇네요
1. setter 대신 의도를 분명히 파악할 수 있게 changeAutorName 메소드를 통해 필드 name 값을 변경할 수 있도록 바꿨습니다.
2. id는 데이터베이스에서 자동으로 관리되기 때문에 변경될 일이 없어 setter가 필요없기 때문에 setId(Long id) 메소드는 삭제해줬습니다.

2024-11-13 17:07 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Author.java
> +public class Author {
클래스에 아무런 생성자도 지정하지 않으면, 자동으로 기본 생성자(매개변수가 없는 생성자)를 자동으로 생성합니다. 하지만 @NoArgsConstructor을 명시적으로 사용하는 것이 좋을 것 같습니다.

2024-11-13 17:42 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/AuthorService.java
> +    private AuthorRepository authorRepository;
두 가지 방법 중 private final이 더 좋은 방법인 거 같습니다. final 키워드를 사용하면 초기화가 된 후에 변경될 수 없음을 보장합니다.

2024-11-14 01:45 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Author.java
> +public class Author {
맞아요.기본 생성자가 자동으로 생성되게되요.
다만, 암시적인 기본 생성자는 접근지정자도 public이기 때문에 불완전한 객체가 만들어질 수 있어요.
그래서, 암시적인 생성자 대신 명시적으로 매개변수가 없는 생성자를 만들고 접근지정자를 protected로 지정해주는게 좋아요.
엔티티 클래스 기본 생성자의 접근지정자에 대해서는 어제 얘기했으니 여기에는 길게 설명안할게요!

2024-11-14 01:49 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/AuthorService.java
> +    private AuthorRepository authorRepository;
좋네요. 
대부분의 상황에서 가능하면 객체를 최대한 불변 상태로 유지하는게 좋아요.
불변 객체의 중요성에 대해 이펙티브 자바에서 나오는 내용을 공유할게요
https://jang-namu.notion.site/17-f3c381d72e7f44d9b0e12f6d497ae58b?pvs=4

2024-11-15 10:55 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/AuthorService.java
> +    }
Entity 클래스는 실제 DB 클래스와 매핑되는 핵심 클래스 입니다. Entity는 데이터베이스와 연관이 깊기 때문에 요청이나 응답 값을 전달하는 클래스로 사용하는 것이 좋지 않습니다. DTO는 계층 간의 데이터 교환이 이루어질 수 있도록 하는 객체입니다. 다양한 계층에서 Entity를 직접적으로 사용하게 된다면 원치 않게 Entity의 속성이 변경시킬 위험이 존재하고 Entity의 모든 속성이 불필요하게 외부에 노출될 가능성이 있습니다. 때문에 DTO의 사용은 당연시되어야 하는 부분입니다. 

AuthorService와 AuthoController의  코드를 DTO를 사용해서 변경했습니다.
![AuthorController](https://github.com/user-attachments/assets/fca048ec-bbf6-41b0-b43b-ec7dcc4667b0)
![AuthorSerivce](https://github.com/user-attachments/assets/1e8a9539-2382-4eca-82c2-aee3299f97f9)

2024-11-15 10:59 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/AuthorController.java
> +    }
@PostMapping
    public AuthorDTO createAuthor(@RequestBody AuthorDTO authorDTO) {
        return authorService.saveAuthor(authorDTO);
    } 이와 같이 AuthorDTO를 사용해서 엔티티의 내부 구조를 숨겼습니다.

2024-11-15 13:01 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/BookController.java
엔드포인트를 /books/search?title = '어린왕자'와 같이 변경하였고 메소드를 특정 단어를 포함하는 책들의 리스트를 반환하는 메소드로 변경하였습니다. 
![BookRepository](https://github.com/user-attachments/assets/eb12bf18-6dda-47a4-be13-dcc06cdf0e0b)
![BookService](https://github.com/user-attachments/assets/bc8d9199-4017-4e46-87d2-0f7ae80c1dfa)
![BookController](https://github.com/user-attachments/assets/9b573c7b-7538-4cf3-b249-b481fe04451b)

2024-11-18 09:01 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/AuthorService.java
> +    }
좋아요, dto로 계층 간 데이터 모델의 분리를 잘 하셨네요.
추가적으로 Optional을 어디서 처리해야 할지에 대해서도 한 번 생각해보면 좋을 것 같아요.
마침 4주차 내용이 이와 관련된 내용이니, 공부하시면서 어떻게 처리하는게 좋을지 고민해보세요!

2024-11-20 09:23 UTC, jang-namu approved these changes, later dismissed
고생하셨습니다!
Optional::map과 HTTP Status Code가 인상깊어서 잘 봤습니다.
전체적으로 큰 오류없이 깔끔하게 잘 작성하신 것 같아요
요구사항이 변경되면서 테이블 간의 관계도 바뀐 것 같아요. 바뀐 부분 반영해서 ERD 올려주세요!

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/BookController.java
> +        }
이 부분을 404로 할지, 200+빈 컬렉션으로 할 지, 명확한 기준이 있는지 저도 헷갈려서 찾아봤는데요.
납득할만한 주장을 찾아서 공유드려요.

요약: 
- 특정 '키'로 검색할 경우. 대상이 존재해야 되는데 없음-> 404 notFound
- 조건과 같이 컬렉션 대상(범위) 검색에서 검색 결과가 없는 경우 -> 200(or 204) + 빈 컬렉션
[What is the correct HTTP status code for search results not found?](https://stackoverflow.com/questions/53543627/what-is-the-correct-http-status-code-for-search-results-not-found)

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/AuthorController.java
> +        return ResponseEntity.noContent().build(); // 204 no content
noContent의 사용은 의미가 정확해서 좋네요!

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Author.java
> +@NoArgsConstructor
NoArgsContsructor의 access 속성을 명시하지 않으면 어떤 접근지정자를 쓰게될까요?

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Author.java
> +    private List<Book> book = new ArrayList<>();
ERD도 함께 변경해서 올려주세요~

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Book.java
> +    private Author author;
FetchType.LAZY까지 잘 작성하셨네요~

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Rental.java
> +    private Book book;
JoinColumn에 대문자, 소문자가 섞여있어요~

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Rental.java
> +    }
메서드 네이밍이 깔끔해서 좋네요!

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/repository/BookRepository.java
> +    List<Book> findByTitleContaining(String title);
잘 작성하셨습니다!

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/BookService.java
> +        return new BookDTO(savedBook);
이 상태에서 author와 publisher의 bookList 상태는 어떻게될까요??

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        Rental rental = new Rental(null, LocalDate.now(), null, member, book);
null을 하드코딩하지 않으려면 어떻게 해야될까요?

2024-11-20 09:23 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        );
생성자 매개변수가 너무 기네요!
어떻게 바꿀수있을까요?

2024-11-21 00:14 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/domain/Author.java
> +@NoArgsConstructor
access 속성을 명시하지 않으면 기본값이 public을 쓰게 됩니다. 하지만 public으로 두게 되면 외부에서의 접근이 쉽기 때문에 @NoArgsConstructor(access = AccessLevel.PROTECTED)로 설정하는 것이 좋을 것 같습니다.

2024-11-21 00:55 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        Rental rental = new Rental(null, LocalDate.now(), null, member, book);
null을 직접 사용하지 않기 위해서 객체를 생성할 때 Builder 패턴을 사용했습니다. rentalDate는 값을 받지 않고 항상 오늘 날짜로 설정되어 생성되게 하였고, returnDate는 기본값 null로 설정하고 member와 book만 받게 설정하였습니다. 
``
@Builder
    protected Rental(Member member, Book book) {
        if(member == null || book == null) {
            throw new IllegalArgumentException("Member와 Book은 필수값입니다.");
        }
        // rentalDate가 null로 전달된 겨우 기본값으로 현재 날짜를 설정
        this.rentalDate = LocalDate.now();
        this.returnDate = null; // 기본값 null
        this.member = member;
        this.book = book;
}
``
``
  // Lombok의 @Builder를 사용해서 Rental 객체 생성
        Rental rental = Rental.builder()
                .member(member)
                .book(book)
                .build();
``

2024-11-21 08:14 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        );
생성자의 매개변수가 길어 코드의 가독성이 떨어집니다. 이를 해결하기 윟 **정적 팩토리 메서드**를 사용했습니다.
![정적 팩토리 메서드](https://github.com/user-attachments/assets/5f510f27-e9ba-440b-936f-99087b2ce3c4)
사진과 같이 정적 팩토리 메서드를 만들고 RentalService의 위의 코드를 ``return RentalDTO.from(savedRental); `` 로 바꿔줬습니다,

2024-11-21 08:38 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/controller/BookController.java
> +        }
위의 코드는 특정 키를 사용해 검색하는 경우가 아닌 조건 기반 검색이기 때문에 결과가 없어도 요청은 성공적으로 처리되었기 때문에 200 OK 와 빈 컬렉션 반환이 적합합니다. 따라서 항상 200 OK를 반환하고 해당 조건에 적합하는 값이 없다면 빈 컬렉션을 반환하기 위해서 원래 코드에서 if문을 제거해줬습니다.

2024-11-21 09:26 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        );
좋네요~ 정적팩토리를 잘 쓰면 코드를 깔끔하게 유지할 수 있을 뿐만 아니라, 추후 생성 로직 변경에도 유연하게 대처할 수 있어요.
다만, 위 상황에서는 Member와 Book이 연관관계로 이어져있기 때문에, LazyInitializationException을 주의깊게 살펴봐야 할 것 같아요!

2024-11-21 09:42 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        Rental rental = new Rental(null, LocalDate.now(), null, member, book);
좋네요~ 빌더를 이용하면 기본값을 넣어서 객체가 생성되는 시점에 불변식을 만족하도록 만들 수 있어요.
도서 관리 시스템의 메인 로직이 책을 대여하는 기능인 만큼 정적팩토리를 통해 의미를 나타내면 어떨까요??
+추가로 생성자의 접근 지정자를 protected로 선언하신 이유가 있으실까요??

2024-11-21 11:46 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/BookService.java
> +        return new BookDTO(savedBook);
JPA에서 양방향 연관관계를 사용하는 경우 메모리 상태와 데이터베이스 상태를 동기화시켜줘야 합니다.Author, Publisher는 Book과 양방향 관계입니다. ``Book book = new Book(bookDTO.getTitle(), author, publisher); `` 이 코드만으로 Author, Publishe4r의 bookList에 해당 Book을 추가하지 않습니다. 명시적으로  ``author.getBookList().add(book);
        publisher.getBookList().add(book);``
추가해준다면 author과 publisher의 bookList에 book이 추가되게 됩니다.

2024-11-21 12:13 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        Rental rental = new Rental(null, LocalDate.now(), null, member, book);
![정적 팩토리 메서드2](https://github.com/user-attachments/assets/797c51b8-6923-4de1-8b2a-4c8304ef2460)
위 사진 처럼 정적 팩토리 메서드를 만들어 RentalService에서  `` Rental rental = Rental.createRental(member, book); `` 를 통해 rental 객체를 생성했습니다.

Q. 생성자의 접근 지정자를 protected로 선언한 이유?
A. public으로 설정하게 되면 외부에서 접근이 가능하기 때문에 더 좁은 범위인 protected로 설정했습니다.

2024-11-21 13:04 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        Rental rental = new Rental(null, LocalDate.now(), null, member, book);
메서드명이 깔끔하네요!
Rental을 상속해서 사용하는 구조가 아니라면,
같은 패키지 내에서도 생성자를 호출하지 못하게 만들 방법은 없을까요??

2024-11-22 12:04 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        );
책을 대여하는 registerRental 메서드는 member와 book 데이터를 별도로 조회하기 때문에 LazyInitializationException이 발생할 가능성이 없다.
책을 반납하는 returnBook 메서드는 Rental 엔티티를 로드한 후,  RentalDTO.from(savedRental) 메서드에서 rental.getMember()와 rental.getBook()을 호출하여 Lazy Loading된 데이터를 참조하기 때문에 LazyInitializationException이 발생할 가능성이 있습니다. RentalRepository에다 
 ``@Query("SELECT r FROM Rental r JOIN FETCH r.book WHERE r.member.id = :memberId AND r.returnDate IS NULL")
    List<Rental> findByMemberIdAndReturnDateIsNull(Long memberId); `` 을 추가해 Fetch Join 쿼리를 사용하였습니다.

2024-11-22 12:09 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        Rental rental = new Rental(null, LocalDate.now(), null, member, book);
Spring JPA에서는 기본 생성자가 반드시 필요합니다.  
 `` @NoArgsConstructor(access = AccessLevel.PRIVATE)
`` 이와 같이 명시해준다면 JPA가 생성자를 호출할 수 없기 때문에 컴파일 오류가 발생합니다. 
찾아보니 중첩 클래스를 사용할 수 있다고 하는데 중첩 클래스를 사용해 JPA에서 사용할 생성자를 중첩 클래스로 두고 외부에서는 Rental 객체를 정적 팩토리 메서드로만 생성할 수 있게 하는게 좋을까요?

2024-11-22 13:45 UTC, jang-namu commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        Rental rental = new Rental(null, LocalDate.now(), null, member, book);
아, 제가 리뷰를 헷갈리게 달았네요.
기본생성자는 protected로 두되, 오버로딩된 생성자는 숨길 수 있지 않을까 하는 내용이었습니다!

2024-11-22 13:52 UTC, chaeeun1103 commented on practice/chaeeun/demo/src/main/java/com/example/demo/service/RentalService.java
> +        Rental rental = new Rental(null, LocalDate.now(), null, member, book);
``@AllArgsConstructor(access = AccessLevel.PRIVATE)``를 PRIVATE로 설정하여 항상 정적 팩토리 메서드를 사용해서만 객체를 생성할 수 있도록 하였습니다!

2024-11-22 13:56 UTC, jang-namu approved these changes

2024-11-22 14:00 UTC, jang-namu approved these changes, later dismissed

2024-11-22 14:51 UTC, merged